nohup: ignoring input
[2025-04-17 15:11:37 +0000] [35878] [INFO] Starting gunicorn 23.0.0
[2025-04-17 15:11:37 +0000] [35878] [ERROR] Connection in use: ('0.0.0.0', 5050)
[2025-04-17 15:11:37 +0000] [35878] [ERROR] connection to ('0.0.0.0', 5050) failed: [Errno 98] Address already in use
[2025-04-17 15:11:38 +[2025-04-17 15:12:21 +0000] [35809] [CRITICAL] WORKER TIMEOUT (pid:35810)
[2025-04-17 15:12:21 +0000] [35810] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/py-app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2025-04-17 15:12:21 +0000] [35810] [INFO] Worker exiting (pid: 35810)
[2025-04-17 15:12:21 +0000] [35884] [INFO] Booting worker with pid: 35884
